package cc.tweaked.vanillaextract.core.mappings;

import net.fabricmc.mappingio.MappingVisitor;

/**
 * The namespaces of mappings to use with a {@link MappingVisitor}.
 */
public final class MappingNamespaces {
    /**
     * The obfuscated names in the main Minecraft jar.
     * <p>
     * These are the ones generated by proguard, and so are typically only a few characters long.
     */
    public static final String OFFICIAL = "official";

    /**
     * The names to actually be used in the workspace by the user.
     */
    public static final String WORKSPACE = "workspace";

    private MappingNamespaces() {
    }
}
