[versions]
fabric-accessWidener = "2.1.0"
fabric-mappingIo = "0.9.1"
fabric-tinyRemapper = "0.14.1"
fabric-unpick = "3.0.0-beta.13"

asm = "9.10.1"
checkerFramework = "3.42.0"
commonsCompress = "1.28.0"
gson = "2.10.1"
jetbrainsAnnotations = "24.1.0"
slf4j = "1.7.0"

# IMPORTANT: Bump in Decompile.java too
vineflower = "1.12.0"

junit = "6.1.3"

shadow = "9.3.0"

[libraries]
fabric-accessWidener = { module = "net.fabricmc:access-widener", version.ref = "fabric-accessWidener" }
fabric-mappingIo = { module = "net.fabricmc:mapping-io", version.ref = "fabric-mappingIo" }
fabric-tinyRemapper = { module = "net.fabricmc:tiny-remapper", version.ref = "fabric-tinyRemapper" }
fabric-unpick = { module = "net.fabricmc.unpick:unpick", version.ref = "fabric-unpick" }
fabric-unpickFormatUtils = { module = "net.fabricmc.unpick:unpick-format-utils", version.ref = "fabric-unpick" }

asm = { module = "org.ow2.asm:asm", version.ref = "asm" }
asm-analysis = { module = "org.ow2.asm:asm-analysis", version.ref = "asm" }
asm-commons = { module = "org.ow2.asm:asm-commons", version.ref = "asm" }
asm-tree = { module = "org.ow2.asm:asm-tree", version.ref = "asm" }
asm-util = { module = "org.ow2.asm:asm-util", version.ref = "asm" }

checkerFramework = { module = "org.checkerframework:checker-qual", version.ref = "checkerFramework" }
commonsCompress = { module = "org.apache.commons:commons-compress", version.ref = "commonsCompress" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
jetbrainsAnnotations = { module = "org.jetbrains:annotations", version.ref = "jetbrainsAnnotations" }
slf4j = { module = "org.slf4j:slf4j-api", version.ref = "slf4j" }
slf4j-simple = { module = "org.slf4j:slf4j-simple", version.ref = "slf4j" }
vineflower = { module = "org.vineflower:vineflower", version.ref = "vineflower" }

junit-jupiter = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit" }
junit-jupiter-launcher = { module = "org.junit.platform:junit-platform-launcher", version.ref = "junit" }

[bundles]
test = ["junit-jupiter"]
testRuntime = ["junit-jupiter-launcher"]

# Dependencies
unshadowedDeps = [
    "asm", "asm-analysis", "asm-commons", "asm-tree", "asm-util", "commonsCompress", "gson"
]

[plugins]
shadow = { id = "com.gradleup.shadow", version.ref = "shadow" }
